blank_issues_enabled: false
contact_links:
  - name: Archon Community
    url: https://thinktank.ottomator.ai/c/archon/30
    about: Please ask questions and start conversations about Archon here in the oTTomator Think Tank!